# This file was generated by GoReleaser. DO NOT EDIT.
cask "7pace-cli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "7pace-cli"], chdir: "."
    end
  end

  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "4fd19bcc901eac40468756c9d7c05088ca772eb550b028c0229cf57a15d60db7"
      url "https://github.com/ville6000/7pace-cli/releases/download/v#{version}/7pace-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ac79dc46f5be7468c6f9c8b537db308f0d623d991bbbdcf920cd76e888f7103"
      url "https://github.com/ville6000/7pace-cli/releases/download/v#{version}/7pace-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "00b7fb8d1ecff912f368c869c0d09d265879c9feae9f4fc5ec7d19ebc20a0f47"
      url "https://github.com/ville6000/7pace-cli/releases/download/v#{version}/7pace-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f43dc4e7777260f82369611d781705e1443c07bdee8ade0faef00135fcc60169"
      url "https://github.com/ville6000/7pace-cli/releases/download/v#{version}/7pace-cli_linux_amd64.tar.gz"
    end
  end

  name "7pace-cli"
  desc "Command line client for 7pace Timetracker"
  homepage "https://github.com/ville6000/7pace-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "7pace-cli"

  # No zap stanza required
end
