# This file was generated by GoReleaser. DO NOT EDIT.
cask "7pace-cli" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "d5619889a6142a584ba29781e89c63ec1cbb2456102c3bb19fb2deaf386c0000"
      url "https://github.com/ville6000/7pace-cli/releases/download/v#{version}/7pace-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4d37c065088357fcf3b3d00c05f1ece27df675cece81f35967ba8af3d64d0343"
      url "https://github.com/ville6000/7pace-cli/releases/download/v#{version}/7pace-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eeafdaa8d03c28a7f0247da4819b72a6a94a22ba571c6ae88510e643ad0257bc"
      url "https://github.com/ville6000/7pace-cli/releases/download/v#{version}/7pace-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb2d2a28d3e47f4d655f80ebf84b0f96ed686c9a0073fa0f7f9efa7518106614"
      url "https://github.com/ville6000/7pace-cli/releases/download/v#{version}/7pace-cli_linux_amd64.tar.gz"
    end
  end

  name "7pace-cli"
  desc "Command line client for 7pace Timetracker"
  homepage "https://github.com/ville6000/7pace-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "7pace-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/7pace-cli"]
    end
  end

  # No zap stanza required
end
