# This file was generated by GoReleaser. DO NOT EDIT.
cask "toggl-cli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "toggl-cli"], chdir: "."
    end
  end

  version "0.27.1"

  on_macos do
    on_arm do
      sha256 "2123cfdb72f96dcca1c28f71dd3b8746db5430660965f125fe0b6a9286613aa1"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1a4c9c2db917f53fd2cf119c925a4b28902af3d42bdfbf9d4fc43376ad1537cb"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1e3f0513204fbe879523f740df617140f0a03c4e33d48fb019a2ff8d64a2a243"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d5f0d4073a12c645767850072b48c4ea5cc4c42afca95b95f154a92722014603"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_linux_amd64.tar.gz"
    end
  end

  name "toggl-cli"
  desc "Command line client for Toggl Track"
  homepage "https://github.com/ville6000/toggl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toggl-cli"

  # No zap stanza required
end
