# This file was generated by GoReleaser. DO NOT EDIT.
cask "toggl-cli" do
  version "0.26.0"

  on_macos do
    on_arm do
      sha256 "e787f9561d9f7e563afa415f06b9592bbc8c57145f1ae95a603e4448c74fd1e7"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "34c05fc5eb9184206914cf04efafa6f60e467fb5f93bb9ec7f2b17b71c4c04ff"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "592283924e17e8b982e39e75e2af3ec47b8dbaa6c24f7a311a543f6373a34693"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "19d07fc462aedfb935f5330b9baf9fdd88e6f5ccf183857bc02608d2f350bdb7"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_linux_amd64.tar.gz"
    end
  end

  name "toggl-cli"
  desc "Command line client for Toggl Track"
  homepage "https://github.com/ville6000/toggl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toggl-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toggl-cli"]
    end
  end

  # No zap stanza required
end
