# This file was generated by GoReleaser. DO NOT EDIT.
cask "toggl-cli" do
  version "0.27.0"

  on_macos do
    on_arm do
      sha256 "5bdf053d1ff48476dd0e196bf99c95cf6863633753da0d36f2edd8efe47162ca"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1348cc23758d1f8cc6cd6eaa9c857d3009e21b0277294d75e414bac38ff76ffa"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b95394f306ed5fc0bafdd0a5691afe7c64e61059ff29aa95d61bee97ca1b4d15"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "08600bdfdcd0e3d2658978cea4c1e6be176e48e6e669dca54ed3c58a543b494e"
      url "https://github.com/ville6000/toggl-cli/releases/download/v#{version}/toggl-cli_linux_amd64.tar.gz"
    end
  end

  name "toggl-cli"
  desc "Command line client for Toggl Track"
  homepage "https://github.com/ville6000/toggl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toggl-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toggl-cli"]
    end
  end

  # No zap stanza required
end
